### ISSUE TITLE
User-Agent in Global Parameters is ignored

### ISSUE THREAD

**Issue by AndrewRocky** [EchoAPI-Team/echoapi-for-vscode-support#1]
VSCode extension ignores User-Agent in Global Parameters.

In Global Parameters (UTF-9 is for test):
![image1](https://github.com/user-attachments/assets/51de73ca-6dff-43f1-9f47-4f22bd42cfe0)

Request in Actual Request (UTF-9 is here):
![image2](https://github.com/user-attachments/assets/e3415ca8-804b-4998-9e89-00722c83ca41)

**Comment by kuwooo** [comment]
We noticed that bug too and we'll get it fixed within this week. Thanks!

**Comment by kuwooo** [comment]
Version 1.4.1 is optimized! Check the Global Param page to set User-Agent using the example below. I’ve also added several new features—can’t wait for your feedback!

![image](https://github.com/user-attachments/assets/af08f40e-9a31-49e1-ab6d-9fb4979ce30c)
