### ISSUE TITLE
Allow Server to be selected per request rather than always using the default

### ISSUE THREAD

**Issue by marc-fez** [EchoAPI-Team/echoapi-for-vscode-support#2]
I can create multiple servers in an environment but I can only access one at a time by setting it as default.
I'm working on a project where I use different servers for auth and request. So the workflow is to connect to auth.domain.com to request a JWT, then connect to service.domain.com to fire a request. 

Ideally, I'd like a drop-down menu in the host box where I can decide which host I should use rather than changing the default in the env file (which is more of an environment thing instead).

**Comment by kuwooo** [comment]
Your feedback is spot-on! We're actually going to improve how this part works real soon.

**Comment by LaraJoyet** [comment]
Could be good if EchoAPI could offer OpenAPI/Swagger YAML/Json import support or similar integration.

**Comment by kuwooo** [comment]
Version 1.4.1 is optimized! You can select the Base URL from the dropdown before the URL. I’ve added more new features too—looking forward to your feedback!

![image](https://github.com/user-attachments/assets/5ed1895f-c3d4-4a1a-9164-8579d8d31f70)

**Comment by marc-fez** [comment]
Perfect, exactly what I was looking for.
