### ISSUE TITLE
Support custom request methods?

### ISSUE THREAD

**Issue by burodeboer** [EchoAPI-Team/echoapi-for-vscode-support#6]
Hi, 
Thanks for creating this great tool/vscode extension!

Is there a way to create a custom request method?
For example: SEARCH

The API that I use supports a SEARCH method (with a JSON formatted query as body).

Couldn't find anything in the docs.

Thanks!

**Comment by kuwooo** [comment]
This feature will be launched soon.

**Comment by kuwooo** [comment]
This feature is live! Use the image below for setup. Thanks for your feedback!

![image](https://github.com/user-attachments/assets/e934e96e-5f28-4848-a2fb-19f774842e39)
